version: '3.8'
services:
  backend:
    build: ./backend
    container_name: symfony-backend
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: ember-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: roadapp
      MYSQL_USER: roadapp
      MYSQL_PASSWORD: roadapp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
