nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:4200', 'http://127.0.0.1:4200', 'http://localhost:8000', 'http://127.0.0.1:8000']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Link']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['*']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
      max_age: 3600